{\rtf1\ansi\ansicpg949\cocoartf2821
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 name: Deploy to GitHub Pages\
\
on:\
  push:\
    branches: ["main"]\
\
permissions:\
  contents: read\
  pages: write\
  id-token: write\
\
concurrency:\
  group: "pages"\
  cancel-in-progress: true\
\
jobs:\
  build:\
    runs-on: ubuntu-latest\
    steps:\
      - name: Checkout\
        uses: actions/checkout@v4\
\
      - name: Setup Node\
        uses: actions/setup-node@v4\
        with:\
          node-version: "20"\
          \
      - name: Install dependencies\
        run: npm install\
\
      - name: Build\
        run: npm run build\
\
      - name: Upload artifact\
        uses: actions/upload-pages-artifact@v3\
        with:\
          path: ./dist\
\
  deploy:\
    environment:\
      name: github-pages\
      url: $\{\{ steps.deployment.outputs.page_url \}\}\
    needs: build\
    runs-on: ubuntu-latest\
    steps:\
      - name: Deploy to GitHub Pages\
        uses: actions/deploy-pages@v4}